apiVersion: v1
appVersion: 1.9.0
description: A Helm chart for ArgoCD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 2.12.0
home: https://github.com/garnercorp/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: seanson
